### ISSUE TITLE
Baid58 parse to TapretCommitment  not work

### ISSUE THREAD

**Issue by crisdut** [BP-WG/bp-core#37] opened 2023-04-19 02:43 UTC
Hi @dr-orlovsky, 

I tried use baid58 parse to TapretCommitment and received the follow error:

```
running 1 test
thread 'tapret::tapscript::test::commiment_serialization' panicked at 'exact size match: Decode(Io(Kind(InvalidInput)))', dbc/src/tapret/tapscript.rs:66:10
``` 

**Test Code**

```rust
#[test]
pub fn tapret_commitment_baid58() {
    let commitment = commitment();
    let _ =  TapretCommitment::from_baid58(commitment.to_baid58()).unwrap();
}
```

**Comment by dr-orlovsky** [comment] 2023-04-28 09:25
This was caused by a bug in strict encoding: https://github.com/strict-types/strict-encoding/pull/13

Fixed in #39

**Closed** 2023-04-28 09:28 UTC
Labels: bug
